name: unison-util-term
github: unisonweb/unison

defaults:
  local: ../../package-defaults.yaml

library:
  source-dirs: .

dependencies:
  - base
  - containers
  - mtl
  - unison-core
  - unison-codebase
