name: unison-util
github: unisonweb/unison

defaults:
  local: ../../package-defaults.yaml

library:
  source-dirs: .

dependencies:
  - base
  - bytestring
  - containers
  - cryptonite
  - lens
  - memory
  - safe
  - sandi
  - text
  - time
  - unliftio
