name: unison-util-serialization

defaults:
  local: ../../package-defaults.yaml

library:
  source-dirs: .

dependencies:
  - base
  - bytes
  - bytestring
  - containers
  - filepath
  - text
  - text-short
  - unliftio
  - vector
