name: unison-codebase
github: unisonweb/unison

defaults:
  local: ../../package-defaults.yaml

library:
  source-dirs: .

dependencies:
  - base
  - containers
  - lens
  - mtl
  - text
  - unison-core
  - unison-util
